import Head from "next/head";
import Image from "next/image";
import { useDispatch, useSelector } from "react-redux";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import {
  addCart,
  deleteCart,
  selectCarts,
  selectuser,
} from "@/redux/cartSlice";
import { menuData } from "@/config/menuData";
import { Badge, Button, message } from "antd";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const [messageApi, contextHolder] = message.useMessage();
  const router = useRouter();
  const dispatch = useDispatch();
  const [loading, setloading] = useState(false);
  const cart = useSelector(selectCarts);
  const user = useSelector(selectuser);
  const query = router?.query;

  const success = () => {
    messageApi.open({
      type: "success",
      content: "Item added in cart sucessfully",
      className: "custom-class",
      style: {
        marginTop: "20vh",
      },
      duration: 3,
    });
  };

  const handleCart = (val, index) => {
    setloading(true);
    let foundItem = cart.some((x) => x.id == index);
    if (!foundItem) {
      let value = { ...val };
      value.qty = 1;
      value.id = index;
      value.date = new Date().toISOString();
      dispatch(addCart(value));
      success();
    }

    setloading(false);
  };
  const allmenuData = [
    ...menuData.Breakfast,
    ...menuData.Dinner,
    ...menuData.Lunch,
    ...menuData.Starters,
  ];

  useEffect(() => {
    if (query?.status === "success") {
      dispatch(deleteCart([]));
    }
  }, [query]);

  const handleLogout = (e) => {
    e.preventDefault();
    localStorage.removeItem("user");
    router.push("/");
    dispatch(deleteCart([]));
  };

  return (
    <>
      <Head>
        <title>Yummy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {/* Navigation*/}
        <nav
          className="navbar navbar-expand-lg navbar-dark fixed-top-home"
          id="mainNav"
        >
          <div className="container">
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarResponsive"
              aria-controls="navbarResponsive"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              Menu
              <i className="fas fa-bars ms-1" />
            </button>
            <div className="collapse navbar-collapse" id="navbarResponsive">
              <ul className="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                <li className="nav-item">
                  <Link className="nav-link" href="/my-order">
                    <Image
                      src="/assets/img/my-orders-icon-25.jpg"
                      className=" "
                      alt=""
                      height={50}
                      width={50}
                    />
                  </Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" href="/cart">
                    <Badge count={cart?.length}>
                      <Image
                        src="/assets/img/icons8-shopping-cart-64.png"
                        className=" "
                        alt=""
                        height={50}
                        width={50}
                      />
                    </Badge>
                  </Link>
                </li>
                <li className="nav-item">
                  <Link
                    className="nav-link pt-4 fw-bold"
                    href="#"
                    onClick={handleLogout}
                  >
                    Logout
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        {/* Masthead*/}
        <header className="masthead">
          <div className="container">
            <div className="masthead-subheading">Welcome To Yummy!</div>
            <div className="masthead-heading text-uppercase">
              It&apos;s Nice To Meet You
            </div>
          </div>
        </header>
        {/* Services*/}
        <section className="page-section" id="services">
          <div className="container">
            <div className="tab-pane fade active show" id="menu-starters">
              <div className="row gy-5">
                {allmenuData.map((items, index) => {
                  return (
                    <div className="col-lg-4 menu-item" key={index}>
                      <a
                        href={`/assets/img/menu/${items.image}`}
                        className="glightbox"
                      >
                        <Image
                          src={`/assets/img/menu/${items.image}`}
                          className="menu-img img-fluid"
                          alt=""
                          height={300}
                          width={300}
                        />
                      </a>
                      <div className="mt-5">
                        <h4>{items.name} </h4>
                        <p className="ingredients">
                          Lorem, deren, trataro, filede, nerada
                        </p>
                        {contextHolder}
                        <div className="cart">
                          {" "}
                          ${items.price}
                          <Button
                            type="button"
                            className="btn btn-warning mt-auto btn-sm  w-48 text-black fw-bold"
                            loading={loading}
                            onClick={() => {
                              handleCart(items, index);
                            }}
                          >
                            Add to cart
                          </Button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </section>

        {/* Footer*/}
        <footer className="footer py-4">
          <div className="container">
            <div className="row align-items-center">
              <div className="col-lg-4 text-lg-start">
                Copyright © Your Website 2022
              </div>
              <div className="col-lg-4 my-3 my-lg-0">
                <a
                  className="btn btn-dark btn-social mx-2"
                  href="#!"
                  aria-label="Twitter"
                >
                  <i className="fab fa-twitter" />
                </a>
                <a
                  className="btn btn-dark btn-social mx-2"
                  href="#!"
                  aria-label="Facebook"
                >
                  <i className="fab fa-facebook-f" />
                </a>
                <a
                  className="btn btn-dark btn-social mx-2"
                  href="#!"
                  aria-label="LinkedIn"
                >
                  <i className="fab fa-linkedin-in" />
                </a>
              </div>
              <div className="col-lg-4 text-lg-end">
                <a className="link-dark text-decoration-none me-3" href="#!">
                  Privacy Policy
                </a>
                <a className="link-dark text-decoration-none" href="#!">
                  Terms of Use
                </a>
              </div>
            </div>
          </div>
        </footer>
        {/* Portfolio Modals*/}
        {/* Portfolio item 1 modal popup*/}
        <div
          className="portfolio-modal modal fade"
          id="portfolioModal1"
          tabIndex={-1}
          role="dialog"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="close-modal" data-bs-dismiss="modal">
                <Image
                  height={45}
                  width={45}
                  src="/assets/img/close-icon.svg"
                  alt="Close modal"
                />
              </div>
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-lg-8">
                    <div className="modal-body">
                      {/* Project details*/}
                      <h2 className="text-uppercase">Project Name</h2>
                      <p className="item-intro text-muted">
                        Lorem ipsum dolor sit amet consectetur.
                      </p>
                      <Image
                        height={600}
                        width={600}
                        className="img-fluid d-block mx-auto"
                        src="/assets/img/portfolio/1.jpg"
                        alt="..."
                      />
                      {/* <img
                        className="img-fluid d-block mx-auto"
                        src="assets/img/portfolio/1.jpg"
                        alt="..."
                      /> */}
                      <p>
                        Use this area to describe your project. Lorem ipsum
                        dolor sit amet, consectetur adipisicing elit. Est
                        blanditiis dolorem culpa incidunt minus dignissimos
                        deserunt repellat aperiam quasi sunt officia expedita
                        beatae cupiditate, maiores repudiandae, nostrum,
                        reiciendis facere nemo!
                      </p>
                      <ul className="list-inline">
                        <li>
                          <strong>Client:</strong>
                          Threads
                        </li>
                        <li>
                          <strong>Category:</strong>
                          Illustration
                        </li>
                      </ul>
                      <button
                        className="btn btn-primary btn-xl text-uppercase"
                        data-bs-dismiss="modal"
                        type="button"
                      >
                        <i className="fas fa-xmark me-1" />
                        Close Project
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Portfolio item 2 modal popup*/}
        <div
          className="portfolio-modal modal fade"
          id="portfolioModal2"
          tabIndex={-1}
          role="dialog"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="close-modal" data-bs-dismiss="modal">
                <Image
                  height={45}
                  width={45}
                  src="/assets/img/close-icon.svg"
                  alt="Close modal"
                />
              </div>
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-lg-8">
                    <div className="modal-body">
                      {/* Project details*/}
                      <h2 className="text-uppercase">Project Name</h2>
                      <p className="item-intro text-muted">
                        Lorem ipsum dolor sit amet consectetur.
                      </p>
                      <Image
                        height={600}
                        width={600}
                        className="img-fluid d-block mx-auto"
                        src="/assets/img/portfolio/2.jpg"
                        alt="..."
                      />
                      <p>
                        Use this area to describe your project. Lorem ipsum
                        dolor sit amet, consectetur adipisicing elit. Est
                        blanditiis dolorem culpa incidunt minus dignissimos
                        deserunt repellat aperiam quasi sunt officia expedita
                        beatae cupiditate, maiores repudiandae, nostrum,
                        reiciendis facere nemo!
                      </p>
                      <ul className="list-inline">
                        <li>
                          <strong>Client:</strong>
                          Explore
                        </li>
                        <li>
                          <strong>Category:</strong>
                          Graphic Design
                        </li>
                      </ul>
                      <button
                        className="btn btn-primary btn-xl text-uppercase"
                        data-bs-dismiss="modal"
                        type="button"
                      >
                        <i className="fas fa-xmark me-1" />
                        Close Project
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Portfolio item 3 modal popup*/}
        <div
          className="portfolio-modal modal fade"
          id="portfolioModal3"
          tabIndex={-1}
          role="dialog"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="close-modal" data-bs-dismiss="modal">
                <Image
                  height={45}
                  width={45}
                  src="/assets/img/close-icon.svg"
                  alt="Close modal"
                />
              </div>
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-lg-8">
                    <div className="modal-body">
                      {/* Project details*/}
                      <h2 className="text-uppercase">Project Name</h2>
                      <p className="item-intro text-muted">
                        Lorem ipsum dolor sit amet consectetur.
                      </p>
                      <Image
                        height={600}
                        width={600}
                        className="img-fluid d-block mx-auto"
                        src="/assets/img/portfolio/3.jpg"
                        alt="..."
                      />
                      <p>
                        Use this area to describe your project. Lorem ipsum
                        dolor sit amet, consectetur adipisicing elit. Est
                        blanditiis dolorem culpa incidunt minus dignissimos
                        deserunt repellat aperiam quasi sunt officia expedita
                        beatae cupiditate, maiores repudiandae, nostrum,
                        reiciendis facere nemo!
                      </p>
                      <ul className="list-inline">
                        <li>
                          <strong>Client:</strong>
                          Finish
                        </li>
                        <li>
                          <strong>Category:</strong>
                          Identity
                        </li>
                      </ul>
                      <button
                        className="btn btn-primary btn-xl text-uppercase"
                        data-bs-dismiss="modal"
                        type="button"
                      >
                        <i className="fas fa-xmark me-1" />
                        Close Project
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Portfolio item 4 modal popup*/}
        <div
          className="portfolio-modal modal fade"
          id="portfolioModal4"
          tabIndex={-1}
          role="dialog"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="close-modal" data-bs-dismiss="modal">
                <Image
                  height={45}
                  width={45}
                  src="/assets/img/close-icon.svg"
                  alt="Close modal"
                />
              </div>
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-lg-8">
                    <div className="modal-body">
                      {/* Project details*/}
                      <h2 className="text-uppercase">Project Name</h2>
                      <p className="item-intro text-muted">
                        Lorem ipsum dolor sit amet consectetur.
                      </p>
                      <Image
                        height={600}
                        width={600}
                        className="img-fluid d-block mx-auto"
                        src="/assets/img/portfolio/4.jpg"
                        alt="..."
                      />
                      <p>
                        Use this area to describe your project. Lorem ipsum
                        dolor sit amet, consectetur adipisicing elit. Est
                        blanditiis dolorem culpa incidunt minus dignissimos
                        deserunt repellat aperiam quasi sunt officia expedita
                        beatae cupiditate, maiores repudiandae, nostrum,
                        reiciendis facere nemo!
                      </p>
                      <ul className="list-inline">
                        <li>
                          <strong>Client:</strong>
                          Lines
                        </li>
                        <li>
                          <strong>Category:</strong>
                          Branding
                        </li>
                      </ul>
                      <button
                        className="btn btn-primary btn-xl text-uppercase"
                        data-bs-dismiss="modal"
                        type="button"
                      >
                        <i className="fas fa-xmark me-1" />
                        Close Project
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Portfolio item 5 modal popup*/}
        <div
          className="portfolio-modal modal fade"
          id="portfolioModal5"
          tabIndex={-1}
          role="dialog"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="close-modal" data-bs-dismiss="modal">
                <Image
                  height={45}
                  width={45}
                  src="/assets/img/close-icon.svg"
                  alt="Close modal"
                />
              </div>
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-lg-8">
                    <div className="modal-body">
                      {/* Project details*/}
                      <h2 className="text-uppercase">Project Name</h2>
                      <p className="item-intro text-muted">
                        Lorem ipsum dolor sit amet consectetur.
                      </p>
                      <Image
                        height={600}
                        width={600}
                        className="img-fluid d-block mx-auto"
                        src="/assets/img/portfolio/5.jpg"
                        alt="..."
                      />
                      <p>
                        Use this area to describe your project. Lorem ipsum
                        dolor sit amet, consectetur adipisicing elit. Est
                        blanditiis dolorem culpa incidunt minus dignissimos
                        deserunt repellat aperiam quasi sunt officia expedita
                        beatae cupiditate, maiores repudiandae, nostrum,
                        reiciendis facere nemo!
                      </p>
                      <ul className="list-inline">
                        <li>
                          <strong>Client:</strong>
                          Southwest
                        </li>
                        <li>
                          <strong>Category:</strong>
                          Website Design
                        </li>
                      </ul>
                      <button
                        className="btn btn-primary btn-xl text-uppercase"
                        data-bs-dismiss="modal"
                        type="button"
                      >
                        <i className="fas fa-xmark me-1" />
                        Close Project
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Portfolio item 6 modal popup*/}
        <div
          className="portfolio-modal modal fade"
          id="portfolioModal6"
          tabIndex={-1}
          role="dialog"
          aria-hidden="true"
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="close-modal" data-bs-dismiss="modal">
                <Image
                  height={45}
                  width={45}
                  src="/assets/img/close-icon.svg"
                  alt="Close modal"
                />
              </div>
              <div className="container">
                <div className="row justify-content-center">
                  <div className="col-lg-8">
                    <div className="modal-body">
                      {/* Project details*/}
                      <h2 className="text-uppercase">Project Name</h2>
                      <p className="item-intro text-muted">
                        Lorem ipsum dolor sit amet consectetur.
                      </p>
                      <Image
                        height={600}
                        width={600}
                        className="img-fluid d-block mx-auto"
                        src="/assets/img/portfolio/6.jpg"
                        alt="..."
                      />
                      <p>
                        Use this area to describe your project. Lorem ipsum
                        dolor sit amet, consectetur adipisicing elit. Est
                        blanditiis dolorem culpa incidunt minus dignissimos
                        deserunt repellat aperiam quasi sunt officia expedita
                        beatae cupiditate, maiores repudiandae, nostrum,
                        reiciendis facere nemo!
                      </p>
                      <ul className="list-inline">
                        <li>
                          <strong>Client:</strong>
                          Window
                        </li>
                        <li>
                          <strong>Category:</strong>
                          Photography
                        </li>
                      </ul>
                      <button
                        className="btn btn-primary btn-xl text-uppercase"
                        data-bs-dismiss="modal"
                        type="button"
                      >
                        <i className="fas fa-xmark me-1" />
                        Close Project
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    </>
  );
}
