import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Tabs } from "antd";
import Menu from "@/components/Menu";
import { menuData } from "@/config/menuData";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {/* Navigation*/}
        <nav
          className="navbar navbar-expand-lg navbar-dark fixed-top"
          id="mainNav"
        >
          <div className="container">
            {/* <a className="navbar-brand" href="#page-top">
              <Image
                src="/assets/img/navbar-logo.svg"
                alt="..."
                width={200}
                height={200}
              />
            </a> */}
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarResponsive"
              aria-controls="navbarResponsive"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              Menu
              <i className="fas fa-bars ms-1" />
            </button>
            <div className="collapse navbar-collapse" id="navbarResponsive">
              <ul className="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                <li className="nav-item">
                  <a className="nav-link" href="#menu">
                    Menu
                  </a>
                </li>

                <li className="nav-item">
                  <a className="nav-link" href="#about">
                    About
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#team">
                    Team
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#contact">
                    Contact
                  </a>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" href="/sign-up">
                    Sign Up
                  </Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" href="/login">
                    Login
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        {/* Masthead*/}
        <header className="masthead">
          <div className="container">
            <div className="masthead-subheading">Welcome To Yummy!</div>
            <div className="masthead-heading text-uppercase">
              Hungary, let&apos;s order some delicious
            </div>
            <Link
              className="btn btn-primary btn-xl text-uppercase "
              href="/sign-up"
            >
              Sign Up For Order
            </Link>
          </div>
        </header>
        {/* Services*/}
        <section className="page-section" id="menu">
          <div className="container">
            <div className="text-center">
              <h2 className="section-heading text-uppercase">Menu</h2>
              <h3 className="section-subheading text-muted">
                Lorem ipsum dolor sit amet consectetur.
              </h3>
            </div>
            <Tabs
              defaultActiveKey="1"
              className="menu"
              centered
              items={[
                {
                  label: <h3 style={{ color: "#000" }}>Starters</h3>,
                  key: "1",
                  children: <Menu menu={menuData.Starters} />,
                },
                {
                  label: <h3 style={{ color: "#000" }}>Breakfast</h3>,
                  key: "2",
                  children: <Menu menu={menuData.Breakfast} />,
                },
                {
                  label: <h3 style={{ color: "#000" }}>Lunch</h3>,
                  key: "3",
                  children: <Menu menu={menuData.Lunch} />,
                },
                {
                  label: <h3 style={{ color: "#000" }}>Dinner</h3>,
                  key: "4",
                  children: <Menu menu={menuData.Dinner} />,
                },
              ]}
            />
          </div>
        </section>
        {/* Portfolio Grid*/}

        {/* About*/}
        <section className="page-section" id="about">
          <div className="container">
            <div className="text-center">
              <h2 className="section-heading text-uppercase">About</h2>
              <h3 className="section-subheading text-muted">
                Lorem ipsum dolor sit amet consectetur.
              </h3>
            </div>
            <ul className="timeline">
              <li>
                {/* <div className="timeline-image">
                  <img
                    className="rounded-circle img-fluid"
                    src="assets/img/about/1.jpg"
                    alt="..."
                  />
                </div> */}
                <div className="timeline-image">
                  <Image
                    height={400}
                    width={700}
                    className="rounded-circle img-fluid"
                    src="/assets/img/about/1.jpg"
                    alt="..."
                  />
                </div>
                <div className="timeline-panel">
                  <div className="timeline-heading">
                    <h4>2009-2011</h4>
                    <h4 className="subheading">Our Humble Beginnings</h4>
                  </div>
                  <div className="timeline-body">
                    <p className="text-muted">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Sunt ut voluptatum eius sapiente, totam reiciendis
                      temporibus qui quibusdam, recusandae sit vero unde, sed,
                      incidunt et ea quo dolore laudantium consectetur!
                    </p>
                  </div>
                </div>
              </li>
              <li className="timeline-inverted">
                <div className="timeline-image">
                  <Image
                    height={400}
                    width={700}
                    className="rounded-circle img-fluid"
                    src="/assets/img/about/2.jpg"
                    alt="..."
                  />
                </div>
                <div className="timeline-panel">
                  <div className="timeline-heading">
                    <h4>March 2011</h4>
                    <h4 className="subheading">An Agency is Born</h4>
                  </div>
                  <div className="timeline-body">
                    <p className="text-muted">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Sunt ut voluptatum eius sapiente, totam reiciendis
                      temporibus qui quibusdam, recusandae sit vero unde, sed,
                      incidunt et ea quo dolore laudantium consectetur!
                    </p>
                  </div>
                </div>
              </li>
              <li>
                <div className="timeline-image">
                  <Image
                    height={400}
                    width={700}
                    className="rounded-circle img-fluid"
                    src="/assets/img/about/3.jpg"
                    alt="..."
                  />
                </div>
                <div className="timeline-panel">
                  <div className="timeline-heading">
                    <h4>December 2015</h4>
                    <h4 className="subheading">Transition to Full Service</h4>
                  </div>
                  <div className="timeline-body">
                    <p className="text-muted">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Sunt ut voluptatum eius sapiente, totam reiciendis
                      temporibus qui quibusdam, recusandae sit vero unde, sed,
                      incidunt et ea quo dolore laudantium consectetur!
                    </p>
                  </div>
                </div>
              </li>
              <li className="timeline-inverted">
                <div className="timeline-image">
                  <Image
                    height={400}
                    width={700}
                    className="rounded-circle img-fluid"
                    src="/assets/img/about/4.jpg"
                    alt="..."
                  />
                </div>
                <div className="timeline-panel">
                  <div className="timeline-heading">
                    <h4>July 2020</h4>
                    <h4 className="subheading">Phase Two Expansion</h4>
                  </div>
                  <div className="timeline-body">
                    <p className="text-muted">
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Sunt ut voluptatum eius sapiente, totam reiciendis
                      temporibus qui quibusdam, recusandae sit vero unde, sed,
                      incidunt et ea quo dolore laudantium consectetur!
                    </p>
                  </div>
                </div>
              </li>
              <li className="timeline-inverted">
                <div className="timeline-image">
                  <h4>
                    Be Part
                    <br />
                    Of Our
                    <br />
                    Story!
                  </h4>
                </div>
              </li>
            </ul>
          </div>
        </section>
        {/* Team*/}
        <section className="page-section bg-light" id="team">
          <div className="container">
            <div className="text-center">
              <h2 className="section-heading text-uppercase">
                Our Amazing Team
              </h2>
              <h3 className="section-subheading text-muted">
                Lorem ipsum dolor sit amet consectetur.
              </h3>
            </div>
            <div className="row">
              <div className="col-lg-4">
                <div className="team-member">
                  <Image
                    height={400}
                    width={700}
                    className="mx-auto rounded-circle"
                    src="/assets/img/team/1.jpg"
                    alt="..."
                  />
                  <h4>Parveen Anand</h4>
                  <p className="text-muted">Lead Designer</p>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Parveen Anand Twitter Profile"
                  >
                    <i className="fab fa-twitter" />
                  </a>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Parveen Anand Facebook Profile"
                  >
                    <i className="fab fa-facebook-f" />
                  </a>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Parveen Anand LinkedIn Profile"
                  >
                    <i className="fab fa-linkedin-in" />
                  </a>
                </div>
              </div>
              <div className="col-lg-4">
                <div className="team-member">
                  <Image
                    height={400}
                    width={700}
                    className="mx-auto rounded-circle"
                    src="/assets/img/team/2.jpg"
                    alt="..."
                  />
                  <h4>Diana Petersen</h4>
                  <p className="text-muted">Lead Marketer</p>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Diana Petersen Twitter Profile"
                  >
                    <i className="fab fa-twitter" />
                  </a>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Diana Petersen Facebook Profile"
                  >
                    <i className="fab fa-facebook-f" />
                  </a>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Diana Petersen LinkedIn Profile"
                  >
                    <i className="fab fa-linkedin-in" />
                  </a>
                </div>
              </div>
              <div className="col-lg-4">
                <div className="team-member">
                  <Image
                    height={400}
                    width={700}
                    className="mx-auto rounded-circle"
                    src="/assets/img/team/3.jpg"
                    alt="..."
                  />
                  <h4>Larry Parker</h4>
                  <p className="text-muted">Lead Developer</p>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Larry Parker Twitter Profile"
                  >
                    <i className="fab fa-twitter" />
                  </a>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Larry Parker Facebook Profile"
                  >
                    <i className="fab fa-facebook-f" />
                  </a>
                  <a
                    className="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Larry Parker LinkedIn Profile"
                  >
                    <i className="fab fa-linkedin-in" />
                  </a>
                </div>
              </div>
            </div>
            <div className="row">
              <div className="col-lg-8 mx-auto text-center">
                <p className="large text-muted">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut
                  eaque, laboriosam veritatis, quos non quis ad perspiciatis,
                  totam corporis ea, alias ut unde.
                </p>
              </div>
            </div>
          </div>
        </section>
        {/* Clients*/}
        {/* <div className="py-5">
          <div className="container">
            <div className="row align-items-center">
              <div className="col-md-3 col-sm-6 my-3">
                <a href="#!">
                  <Image
                    height={400}
                    width={700}
                    className="img-fluid img-brand d-block mx-auto"
                    src="/assets/img/logos/microsoft.svg"
                    alt="..."
                    aria-label="Microsoft Logo"
                  />
                </a>
              </div>
              <div className="col-md-3 col-sm-6 my-3">
                <a href="#!">
                  <Image
                    height={400}
                    width={700}
                    className="img-fluid img-brand d-block mx-auto"
                    src="/assets/img/logos/google.svg"
                    alt="..."
                    aria-label="Google Logo"
                  />
                </a>
              </div>
              <div className="col-md-3 col-sm-6 my-3">
                <a href="#!">
                  <Image
                    height={400}
                    width={700}
                    className="img-fluid img-brand d-block mx-auto"
                    src="/assets/img/logos/facebook.svg"
                    alt="..."
                    aria-label="Facebook Logo"
                  />
                </a>
              </div>
              <div className="col-md-3 col-sm-6 my-3">
                <a href="#!">
                  <Image
                    height={400}
                    width={700}
                    className="img-fluid img-brand d-block mx-auto"
                    src="/assets/img/logos/ibm.svg"
                    alt="..."
                    aria-label="IBM Logo"
                  />
                </a>
              </div>
            </div>
          </div>
        </div> */}
        {/* Contact*/}
        <section className="page-section" id="contact">
          <div className="container">
            <div className="text-center">
              <h2 className="section-heading text-uppercase">Contact Us</h2>
              <h3 className="section-subheading text-muted">
                Lorem ipsum dolor sit amet consectetur.
              </h3>
            </div>
            {/* * * * * * * * * * * * * * * **/}
            {/* * * SB Forms Contact Form * **/}
            {/* * * * * * * * * * * * * * * **/}
            {/* This form is pre-integrated with SB Forms.*/}
            {/* To make this form functional, sign up at*/}
            {/* https://startbootstrap.com/solution/contact-forms*/}
            {/* to get an API token!*/}
            {/* <form id="contactForm" data-sb-form-api-token="API_TOKEN">
              <div className="row align-items-stretch mb-5">
                <div className="col-md-6">
                  <div className="form-group">
                   
                    <input
                      className="form-control"
                      id="name"
                      type="text"
                      placeholder="Your Name *"
                      data-sb-validations="required"
                    />
                    <div
                      className="invalid-feedback"
                      data-sb-feedback="name:required"
                    >
                      A name is required.
                    </div>
                  </div>
                  <div className="form-group">
                 
                    <input
                      className="form-control"
                      id="email"
                      type="email"
                      placeholder="Your Email *"
                      data-sb-validations="required,email"
                    />
                    <div
                      className="invalid-feedback"
                      data-sb-feedback="email:required"
                    >
                      An email is required.
                    </div>
                    <div
                      className="invalid-feedback"
                      data-sb-feedback="email:email"
                    >
                      Email is not valid.
                    </div>
                  </div>
                  <div className="form-group mb-md-0">
                
                    <input
                      className="form-control"
                      id="phone"
                      type="tel"
                      placeholder="Your Phone *"
                      data-sb-validations="required"
                    />
                    <div
                      className="invalid-feedback"
                      data-sb-feedback="phone:required"
                    >
                      A phone number is required.
                    </div>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="form-group form-group-textarea mb-md-0">
         
                    <textarea
                      className="form-control"
                      id="message"
                      placeholder="Your Message *"
                      data-sb-validations="required"
                      defaultValue={""}
                    />
                    <div
                      className="invalid-feedback"
                      data-sb-feedback="message:required"
                    >
                      A message is required.
                    </div>
                  </div>
                </div>
              </div>
              
              <div className="d-none" id="submitSuccessMessage">
                <div className="text-center text-white mb-3">
                  <div className="fw-bolder">Form submission successful!</div>
                  To activate this form, sign up at
                  <br />
                  <a href="https://startbootstrap.com/solution/contact-forms">
                    https://startbootstrap.com/solution/contact-forms
                  </a>
                </div>
              </div>
            
              <div className="d-none" id="submitErrorMessage">
                <div className="text-center text-danger mb-3">
                  Error sending message!
                </div>
              </div>
             
              <div className="text-center">
                <button
                  className="btn btn-primary btn-xl text-uppercase disabled"
                  id="submitButton"
                  type="submit"
                >
                  Send Message
                </button>
              </div>
            </form> */}
          </div>
        </section>
        {/* Footer*/}
        <footer className="footer py-4">
          <div className="container">
            <div className="row align-items-center">
              <div className="col-lg-4 text-lg-start">
                Copyright © Your Website 2022
              </div>
              <div className="col-lg-4 my-3 my-lg-0">
                <a
                  className="btn btn-dark btn-social mx-2"
                  href="#!"
                  aria-label="Twitter"
                >
                  <i className="fab fa-twitter" />
                </a>
                <a
                  className="btn btn-dark btn-social mx-2"
                  href="#!"
                  aria-label="Facebook"
                >
                  <i className="fab fa-facebook-f" />
                </a>
                <a
                  className="btn btn-dark btn-social mx-2"
                  href="#!"
                  aria-label="LinkedIn"
                >
                  <i className="fab fa-linkedin-in" />
                </a>
              </div>
              <div className="col-lg-4 text-lg-end">
                <a className="link-dark text-decoration-none me-3" href="#!">
                  Privacy Policy
                </a>
                <a className="link-dark text-decoration-none" href="#!">
                  Terms of Use
                </a>
              </div>
            </div>
          </div>
        </footer>
      </>
    </>
  );
}
